### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by foobarto** [sasa1977/fsm#1]
Thanks for yet another great project! Have you considered tagging it? Dependency management is always so much easier if everything has tags/versions.

**Comment by sasa1977** [comment]
Hi,

First of all, sorry for the late reply. I'm on vacations, and I didn't have access to my laptop for past 10 days.

I agree that I should tag versions. When I come back home next week, I'll try to add tags for existing versions.

That said, if you're fetching the dependency via hex, then I think you should be fine, since there versions are tagged, and you can fetch particular version (see [here](https://hex.pm/packages/fsm)).

**Comment by sasa1977** [comment]
I have now added tags to previous versions.
