### ISSUE TITLE
trying to define a reusable module with dynamic definitions

### ISSUE THREAD

**Issue by andreapavoni** [sasa1977/fsm#2]
Hi there,

thank you for this package (and your book as well :P). following the example in the README, I'm trying to create a reusable module with dynamic definitions, but perhaps I'm leaving some bit behind me :P

```
defmodule StateMachine do
  defmacro __using__(opts) do
    quote do
      use Fsm, initial_state: unquote(opts[:initial_state])

      for {state, transitions} <- unquote(opts[:states]) do
        defstate state do
          for {event, target_state} <- transitions do
            quote do
              defevent unquote(event) do
                next_state(unquote(target_state))
              end
            end
          end
        end
      end
    end
  end
end
```

then I wrote a simple test for this

```
defmodule StateMachineTest do
  use ExSpec

  defmodule TestOrder do
    use Nova.StateMachine, [states: [
      cart: [next: :address],
      address: [next: :payment],
      payment: [next: :confirm],
      confirm: [next: :completed]
    ], initial_state: :cart]
  end


  test "it works" do
    order = TestOrder.new

    IO.inspect TestOrder.__info__(:functions)

    assert(order |> TestOrder.state == :cart)

    order = order |> TestOrder.next
    assert(order |> TestOrder.state == :address)

    order = order |> TestOrder.next
    assert(order |> TestOrder.state == :payment)

    order = order |> TestOrder.next
    assert(order |> TestOrder.state == :confirm)

    order = order |> TestOrder.next
    assert(order |> TestOrder.state == :complete)
  end
end
```

however, it doesn't work because the event `next` is not recognized. I'm sure there's some error in my code. can you please help me?

I know this isn't StackOverflow, however it might be a useful addition to README :P

thank you in advance for eventual help :-)

**Comment by sasa1977** [comment]
Your immediate problem lies in this line:

```
defstate state do
```

Here, you're defining the state which is called `:state`. You need to have `unquote(state)` there. Unfortunately, that won't work since you're inside a quote block, but many module-level macros such as `def` or `use` implicitly open a new quoted block, so your unquote can't access `state` var. 

The solution is to pass `opt` via `bind_quoted`. This will pass `opts` to the quoted context, and leave `unquote` untouched (i.e. they won't inject anything, but will be resolved in the later macro expansion pass). 

This also removes the need for the inner most `quote` block in your code (which wouldn't work anyway).

The fixed version which works at least for the first `next` transition looks like:

```
defmodule StateMachine do
  defmacro __using__(opts) do
    quote bind_quoted: [opts: opts] do
      use Fsm, initial_state: unquote(opts[:initial_state])

      for {state, transitions} <- opts[:states] do
        defstate unquote(state) do
          for {event, target_state} <- transitions do
            defevent unquote(event) do
              next_state(unquote(target_state))
            end
          end
        end
      end
    end
  end
end
```

I've discussed this topic a bit in [the part 6 of my macro series](http://www.theerlangelist.com/2014/07/understanding-elixir-macros-part-6.html). The post is pretty involved, because there are many nuances when it comes to macros. If you already didn't, I suggest reading the entire series. In particular, first posts in the series should clear up some things about macros. At least that was the intention :-)

**Comment by andreapavoni** [comment]
Thank you so much for the explanation/solution! I'm going to read your macro series right now :-)
